apiVersion: v1 
kind: Service 
metadata:
  name: node-svc
  namespace: test-ns
spec:
  slector:
    name: node-deployment
    tier: app
  ports:
    - protocol: TCP 
      port: 3001
      targetPort: 3000
    type: LoadBalancer      
